version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRESUSER=${POSTGRESUSER}
      - POSTGRESPASS=${POSTGRESPASS}
      - POSTGRESDB=${POSTGRESDB}
    command: bash -c "alembic upgrade head"